import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { getDocumentProxy } from 'unpdf';

import { readLayout, toMarkedText, ANNOTATION_MARK } from '@/lib/cv/import/layout';
import { isKnownSectionHeading, parseCvText } from '@/lib/cv/import/parse';

/**
 * Layout-aware extraction, against the CV that motivated it.
 *
 * The file is a two-page French CV generated by a template: headings set 1pt larger than the
 * body, dates and cities right-aligned, bullet glyphs with no space after them. Read as a flat
 * string it defeated every heuristic in `parse.ts` — the point of these tests is that the
 * facts it needs are measurable, so they should be measured rather than guessed.
 */

/*
 * Invented content, real layout.
 *
 * The document that exposed these bugs was a person's actual CV — name, email, phone,
 * employers. That does not belong in a repository. The fixture reproduces what mattered
 * (heading size one point above body, right-aligned dates and cities, bullet glyphs with no
 * space, a section with no matching field) around a person who does not exist. It is
 * regenerated by `scripts/make-import-fixture.mjs`.
 */
const FIXTURE = 'tests/fixtures/two-column-fr.pdf';

async function layout() {
  const bytes = new Uint8Array(readFileSync(FIXTURE));
  return readLayout((await getDocumentProxy(bytes)) as never);
}

describe('layout extraction', () => {
  it('identifies section headings by font size, not by their wording', async () => {
    const marked = toMarkedText(await layout(), isKnownSectionHeading);
    const headings = marked
      .split('\n')
      .filter((line) => line.startsWith('# '))
      .map((line) => line.slice(2));

    expect(headings).toEqual([
      'Profile',
      'EXPERIENCE PROFESIONNELLE',
      'FORMATION',
      'COMPÉTENCES TECHNIQUES',
      'COMPÉTENCES LINGUISTIQUES',
      "Centre d'Intérêt",
    ]);
  });

  it('leaves the name and job title out of the headings', async () => {
    /*
     * They are set larger than the headings, not equal to them, and they appear once each.
     * Marking them as sections emptied the header block the contact parser reads — no name,
     * no email, no phone, on a CV that plainly had all three.
     */
    const marked = toMarkedText(await layout(), isKnownSectionHeading);
    // It may carry the entry mark — it is set larger than the body, which is what that mark
    // means — but it must never be a *section*, or the header block the contact parser
    // reads is empty and the CV comes back with no name, email or phone.
    const asLines = marked.split('\n');
    expect(asLines.filter((line) => line.startsWith('# '))).not.toContain('# Nadia Belhaj');
    expect(asLines[0]).toContain('Nadia Belhaj');
  });

  it('marks the right-aligned city as an annotation, not as a line of its own', async () => {
    const marked = toMarkedText(await layout(), isKnownSectionHeading);
    expect(marked).toContain(`${ANNOTATION_MARK}Rabat`);
  });

  it('keeps words apart and does not glue them together', async () => {
    // pdf.js emits the spaces between words as separate runs; dropping them produced
    // `Chefdeprojettransverse(CIRCETMOROCCO)`.
    const marked = toMarkedText(await layout(), isKnownSectionHeading);
    expect(marked).toContain('Cheffe de projet transverse');
  });
});

describe('the whole pipeline on that CV', () => {
  async function parsed() {
    return parseCvText(toMarkedText(await layout(), isKnownSectionHeading), { locale: 'fr' });
  }

  it('reads every job, with its employer and dates', async () => {
    const { data } = await parsed();
    expect(data.experience).toHaveLength(2);
    expect(data.experience?.map((job) => job.company)).toEqual(['ORBINET MAROC', 'TALVENT MAROC']);
    expect(data.experience?.[0]?.startDate).toBe('2024-11');
    expect(data.experience?.[0]?.current).toBe(true);
    expect(data.experience?.[1]?.endDate).toBe('2024-10');
  });

  it('reads every qualification, with its school', async () => {
    const { data } = await parsed();
    expect(data.education).toHaveLength(2);
    expect(data.education?.[0]?.degree).toBe('Master Management de Projet');
    expect(data.education?.[0]?.institution).toBe('Institut Veranne');
    // The school sits on the line *below* the degree, because the date is set beside it.
    expect(data.education?.[1]?.degree).toBe('Licence Génie Logiciel Web et Mobiles');
    expect(data.education?.[1]?.institution).toContain('École nationale');
  });

  it('keeps the contact block', async () => {
    const { data } = await parsed();
    expect(data.personal?.firstName).toBe('Nadia');
    expect(data.personal?.lastName).toBe('Belhaj');
    expect(data.personal?.email).toBe('nadia.belhaj@example.com');
  });

  it('separates languages from skills', async () => {
    const { data } = await parsed();
    expect(data.languages?.map((language) => language.name)).toEqual([
      'Arabe',
      'Français',
      'Anglais',
    ]);
  });

  it('keeps a section it has no field for, rather than dropping it', async () => {
    // `Centre d'Intérêt` maps onto the `interests` id, which nothing reads — so it used to
    // vanish after being correctly identified, which is the worst of both outcomes.
    const { data, report } = await parsed();
    expect(report.custom.length).toBeGreaterThan(0);
    expect(JSON.stringify(data.customSections)).toContain('Randonnée');
  });
});
